<?php
/**
 * File that holds example custom post type registration details
 *
 * @since 1.0.0
 * @package WP_Boilerplate_Plugin\Custom_Post_Type
 */

declare( strict_types=1 );

namespace WP_Boilerplate_Plugin\Custom_Post_Type;

use WP_Boilerplate_Plugin\Custom_Fields\Custom_Field;

/**
 * Class that initializes the example custom post type and taxonomy
 *
 * @since 1.0.0
 */
final class Example_Post_Type extends Base_Post_Type {

  /**
   * The custom post type slug
   *
   * @var string
   */
   const POST_TYPE_SLUG = 'example-cpt';

  /**
   * The capability type string
   *
   * @var string
   */
   const CAPABILITY_TYPE = 'post';

  /**
   * The custom post type menu icon
   *
   * @var string
   */
   const MENU_ICON = 'dashicons-list-view';

  /**
   * Get the slug to use for the custom post type.
   *
   * @return string Custom post type slug.
   */
  protected function get_post_type_slug() : string {
    return self::POST_TYPE_SLUG;
  }

  /**
   * Get the arguments that configure the custom post type.
   *
   * @return array Array of arguments.
   */
  protected function get_post_type_arguments() : array {
    $nouns = [
      Label_Generator::SINGULAR_NAME_UC => esc_html_x( 'Example', 'post type upper case singular name', 'wp-boilerplate-plugin' ),
      Label_Generator::SINGULAR_NAME_LC => esc_html_x( 'example', 'post type lower case singular name', 'wp-boilerplate-plugin' ),
      Label_Generator::PLURAL_NAME_UC   => esc_html_x( 'Examples', 'post type upper case plural name', 'wp-boilerplate-plugin' ),
      Label_Generator::PLURAL_NAME_LC   => esc_html_x( 'examples', 'post type lower case plural name', 'wp-boilerplate-plugin' ),
    ];

    return [
      'label'              => $nouns[ Label_Generator::SINGULAR_NAME_UC ],
      'labels'             => ( new Label_Generator() )->get_generated_labels( $nouns ),
      'public'             => true,
      'menu_position'      => 50,
      'menu_icon'          => self::MENU_ICON,
      'supports'           => array( 'title', 'revisions', 'editor' ),
      'has_archive'        => false,
      'show_in_rest'       => true,
      'publicly_queryable' => true,
      'capability_type'    => self::CAPABILITY_TYPE,
      'map_meta_cap'       => true,
      'can_export'         => true,
    ];
  }

  /**
   * Get the custom fields to add to a response.
   *
   * Add the fields from generated by ACF as a custom field.
   *
   * @return array Array of custom field schema.
   */
  protected function get_custom_rest_fields() : array {
    return [];
  }
}
